services:
  engine:
    image: ghcr.io/lavavc/automated-infra:latest
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    env_file: .env
    environment:
      HOST: "0.0.0.0"
    volumes:
      - ./data:/app/data
