"""StorageBackend protocol — the interface ArbitrageEngine requires from the DB layer."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    async def insert_action(self, **kwargs) -> int | None: ...
    async def insert_alert(self, **kwargs) -> int | None: ...
    async def insert_arb_opportunity(self, **kwargs) -> int | None: ...
    async def get_recent_prices(self, limit: int) -> list: ...
    async def get_arb_history(self, **kwargs) -> list: ...
