"""Storage protocol consumed by the arbitrage engine and related services."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    async def insert_action(self, **kwargs) -> int | None: ...
    async def insert_alert(self, **kwargs) -> int | None: ...
    async def insert_arbitrage_opportunity(self, opp) -> None: ...
    async def update_arbitrage_opportunity(self, opp_id: str, **kwargs) -> None: ...
    async def insert_dex_arbitrage_opportunity(self, opp) -> None: ...
    async def update_dex_arbitrage_execution_state(self, opp_id: str, **kwargs) -> None: ...
    async def get_recent_prices(self, limit: int) -> list: ...
    async def get_dex_arbitrage_opportunity(self, opp_id: str): ...
    async def get_arbitrage_opportunity(self, opp_id: str): ...
    async def get_arbitrage_history(self, **kwargs) -> list: ...
    async def get_arbitrage_stats(self, from_ts: int) -> dict: ...
    async def get_active_dex_opportunity(self, direction: str) -> str | None: ...
    async def expire_old_dex_arbitrage_opportunities(self, cutoff_ts: int) -> None: ...
    async def upsert_arbitrage_history_event(self, event) -> None: ...
    async def insert_price_snapshot(self, quote, metadata=None) -> None: ...
